#!/bin/bash
export API_DIR=~/Conjur/python_test/py_client

docker stop py_test

echo "Running Python Example..."
docker run -d --rm					\
  --name py_test					\
  -v ${API_DIR}:/py_client				\
  -v ${PWD}/python_client.py:/python_client.py		\
  -v ${PWD}/policy:/config/policy			\
  -v "/Users/josephhunt/Conjur/cybrsm-demos/etc/conjur-master-minikube-dev.pem:/config/conjur-cert.pem"	\
  -e "CONJUR_APPLIANCE_HOSTNAME=conjur-master-minikube"		\
  -e "CONJUR_ACCOUNT=dev"					\
  -e "CONJUR_AUTHN_LOGIN=admin"					\
  -e "CONJUR_AUTHN_API_KEY=$(keyring get conjur adminpwd)"	\
  --add-host "conjur-master-minikube:192.168.59.100"		\
  k8s-app:alpine						\
  bash -c "
    python -m pip install -e /py_client ; 			\
    sleep infinity
  "

docker exec -it --user root py_test bash

