#!/bin/bash

# Conjur Open API spec directory
#   see: https://github.com/cyberark/conjur-openapi-spec
GEN_DIR=../conjur-openapi-spec-main

# Conjur service configuration variables
CONJUR_ACCOUNT=<conjur-account>
CONJUR_APPLIANCE_HOSTNAME=<conjur-hostname>
CONJUR_HOST_IP_ADDRESS=<conjur-host-ip-address>
CONJUR_CERT=<path-to-my-conjur-server-pem-file>
CONJUR_AUTHN_LOGIN=<admin-user-id>
CONJUR_AUTHN_API_KEY=<admin-user-password>

##############################################################
# You should not need to edit anything below to run the demo.
##############################################################

# Generated client directory
API_DIR=${PWD}/py_client

pushd $GEN_DIR
./bin/generate_client -e -l python -o $API_DIR
popd


# mount point for scripts and starting directory
WORKDIR=/test/

docker run -d --rm						\
  -e "DEBUG=False"						\
  --name py_test						\
  -v ${API_DIR}:${WORKDIR}py_client				\
  -v ${PWD}/bin/init_python.sh:${WORKDIR}init_python.sh		\
  -v ${PWD}/bin/python_client.py:${WORKDIR}python_client.py	\
  -v ${PWD}/policy:${WORKDIR}/policy				\
  -v "${CONJUR_CERT}:${WORKDIR}conjur-cert.pem"			\
  -e "CONJUR_APPLIANCE_HOSTNAME=${CONJUR_APPLIANCE_HOSTNAME}"	\
  -e "CONJUR_ACCOUNT=${CONJUR_ACCOUNT}"				\
  -e "CONJUR_AUTHN_LOGIN=${CONJUR_AUTHN_LOGIN}"			\
  -e "CONJUR_AUTHN_API_KEY=${CONJUR_AUTHN_API_KEY}"		\
  --workdir ${WORKDIR}						\
  --add-host "${CONJUR_APPLIANCE_HOSTNAME}:${CONJUR_HOST_IP_ADDRESS}"	\
  python:3							\
  bash -c "sleep infinity"

docker exec -it --user root py_test bash

echo "Deleting py_test container as background job..."
docker stop py_test > /dev/null 2>&1 &
