# coding: utf-8

"""
    Conjur

    This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Contact: conj_maintainers@cyberark.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from conjur.configuration import Configuration


class ResourcePermissions(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'policy': 'str',
        'privilege': 'str',
        'role': 'str'
    }

    attribute_map = {
        'policy': 'policy',
        'privilege': 'privilege',
        'role': 'role'
    }

    def __init__(self, policy=None, privilege=None, role=None, local_vars_configuration=None):  # noqa: E501
        """ResourcePermissions - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._policy = None
        self._privilege = None
        self._role = None
        self.discriminator = None

        if policy is not None:
            self.policy = policy
        if privilege is not None:
            self.privilege = privilege
        if role is not None:
            self.role = role

    @property
    def policy(self):
        """Gets the policy of this ResourcePermissions.  # noqa: E501


        :return: The policy of this ResourcePermissions.  # noqa: E501
        :rtype: str
        """
        return self._policy

    @policy.setter
    def policy(self, policy):
        """Sets the policy of this ResourcePermissions.


        :param policy: The policy of this ResourcePermissions.  # noqa: E501
        :type: str
        """

        self._policy = policy

    @property
    def privilege(self):
        """Gets the privilege of this ResourcePermissions.  # noqa: E501


        :return: The privilege of this ResourcePermissions.  # noqa: E501
        :rtype: str
        """
        return self._privilege

    @privilege.setter
    def privilege(self, privilege):
        """Sets the privilege of this ResourcePermissions.


        :param privilege: The privilege of this ResourcePermissions.  # noqa: E501
        :type: str
        """

        self._privilege = privilege

    @property
    def role(self):
        """Gets the role of this ResourcePermissions.  # noqa: E501


        :return: The role of this ResourcePermissions.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this ResourcePermissions.


        :param role: The role of this ResourcePermissions.  # noqa: E501
        :type: str
        """

        self._role = role

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourcePermissions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ResourcePermissions):
            return True

        return self.to_dict() != other.to_dict()
