# coding: utf-8

"""
    Conjur

    This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Contact: conj_maintainers@cyberark.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import conjur
from conjur.api.roles_api import RolesApi  # noqa: E501
from conjur.rest import ApiException


class TestRolesApi(unittest.TestCase):
    """RolesApi unit test stubs"""

    def setUp(self):
        self.api = conjur.api.roles_api.RolesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_member_to_role(self):
        """Test case for add_member_to_role

        Update or modify an existing role membership  # noqa: E501
        """
        pass

    def test_remove_member_from_role(self):
        """Test case for remove_member_from_role

        Deletes an existing role membership  # noqa: E501
        """
        pass

    def test_show_role(self):
        """Test case for show_role

        Get role information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
