# coding: utf-8

"""
    Conjur

    This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Contact: conj_maintainers@cyberark.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import conjur
from conjur.api.resources_api import ResourcesApi  # noqa: E501
from conjur.rest import ApiException


class TestResourcesApi(unittest.TestCase):
    """ResourcesApi unit test stubs"""

    def setUp(self):
        self.api = conjur.api.resources_api.ResourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_show_resource(self):
        """Test case for show_resource

        Shows a description of a single resource.  # noqa: E501
        """
        pass

    def test_show_resources_for_account(self):
        """Test case for show_resources_for_account

        Lists resources within an organization account.  # noqa: E501
        """
        pass

    def test_show_resources_for_all_accounts(self):
        """Test case for show_resources_for_all_accounts

        Lists resources within an organization account.  # noqa: E501
        """
        pass

    def test_show_resources_for_kind(self):
        """Test case for show_resources_for_kind

        Lists resources of the same kind within an organization account.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
