# coding: utf-8

"""
    Conjur

    This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Contact: conj_maintainers@cyberark.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import conjur
from conjur.models.who_am_i import WhoAmI  # noqa: E501
from conjur.rest import ApiException

class TestWhoAmI(unittest.TestCase):
    """WhoAmI unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test WhoAmI
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = conjur.models.who_am_i.WhoAmI()  # noqa: E501
        if include_optional :
            return WhoAmI(
                account = 'dev', 
                client_ip = '127.0.0.1', 
                token_issued_at = '2017-08-04T22:27:20+00:00', 
                user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36', 
                username = 'admin'
            )
        else :
            return WhoAmI(
        )

    def testWhoAmI(self):
        """Test WhoAmI"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
