# coding: utf-8

"""
    Conjur

    This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Contact: conj_maintainers@cyberark.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import conjur
from conjur.api.secrets_api import SecretsApi  # noqa: E501
from conjur.rest import ApiException


class TestSecretsApi(unittest.TestCase):
    """SecretsApi unit test stubs"""

    def setUp(self):
        self.api = conjur.api.secrets_api.SecretsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_secret(self):
        """Test case for create_secret

        Creates a secret value within the specified variable.  # noqa: E501
        """
        pass

    def test_get_secret(self):
        """Test case for get_secret

        Fetches the value of a secret from the specified Secret.  # noqa: E501
        """
        pass

    def test_get_secrets(self):
        """Test case for get_secrets

        Fetch multiple secrets  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
