# coding: utf-8

"""
    Conjur

    This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Contact: conj_maintainers@cyberark.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import conjur
from conjur.api.status_api import StatusApi  # noqa: E501
from conjur.rest import ApiException


class TestStatusApi(unittest.TestCase):
    """StatusApi unit test stubs"""

    def setUp(self):
        self.api = conjur.api.status_api.StatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_authenticators(self):
        """Test case for get_authenticators

        Details about which authenticators are on the Conjur Server  # noqa: E501
        """
        pass

    def test_get_gcp_authenticator_status(self):
        """Test case for get_gcp_authenticator_status

        Details whether an authentication service has been configured properly  # noqa: E501
        """
        pass

    def test_get_service_authenticator_status(self):
        """Test case for get_service_authenticator_status

        Details whether an authentication service has been configured properly  # noqa: E501
        """
        pass

    def test_health(self):
        """Test case for health

        Health info about conjur  # noqa: E501
        """
        pass

    def test_info(self):
        """Test case for info

        Basic information about the Conjur Enterprise server  # noqa: E501
        """
        pass

    def test_remote_health(self):
        """Test case for remote_health

        Health info about a given Conjur Enterprise server  # noqa: E501
        """
        pass

    def test_who_am_i(self):
        """Test case for who_am_i

        Provides information about the client making an API request.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
