# coding: utf-8

"""
    Conjur

    This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Contact: conj_maintainers@cyberark.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import conjur
from conjur.api.public_keys_api import PublicKeysApi  # noqa: E501
from conjur.rest import ApiException


class TestPublicKeysApi(unittest.TestCase):
    """PublicKeysApi unit test stubs"""

    def setUp(self):
        self.api = conjur.api.public_keys_api.PublicKeysApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_show_public_keys(self):
        """Test case for show_public_keys

        Shows all public keys for a resource.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
